/**
 * Clinical Grounding, Privacy & Hallucination Defense Guardrails Engine
 *
 * Guardrail Layers:
 * 1. PII / CNIC / Phone / IBAN Data Privacy Masking (with Pakistani Emergency Hotline whitelist).
 * 2. Unauthorized Prescription & Definitive Diagnosis Refusal Defense.
 * 3. Numerical Boundary & Guideline Grounding Verification.
 * 4. Citation Whitelist & Provenance Integrity Verification.
 */

// Whitelist for Pakistan Emergency & Crisis Hotlines (Do NOT redact these)
const ALLOWED_HOTLINE_PATTERNS = [
  /0311-?7786264/g, // Umang
  /0800-?22444/g,   // Rozan
  /0303-?4442288/g, // Rozan Mobile
  /\b1122\b/g,      // Rescue 1122
  /\b115\b/g,       // Edhi Ambulance
  /\b1020\b/g,      // Chhipa Ambulance
  /\b15\b/g,        // Police 15
  /\b16\b/g,        // Fire Brigade 16
  /\b1166\b/g,      // Sehat Sahulat / Health 1166
];

/**
 * Sanitize PII from text before logging or storing, preserving emergency hotlines.
 *
 * @param {string} text
 * @returns {string} Sanitized text
 */
function sanitizePii(text) {
  if (!text || typeof text !== 'string') return text;

  let sanitized = text;

  // 1. Temporarily replace allowed hotlines with placeholders
  const hotlineReplacements = [];
  ALLOWED_HOTLINE_PATTERNS.forEach((regex, idx) => {
    sanitized = sanitized.replace(regex, (match) => {
      const placeholder = `__ALLOWED_HOTLINE_${idx}_${hotlineReplacements.length}__`;
      hotlineReplacements.push({ placeholder, match });
      return placeholder;
    });
  });

  // 2. Redact Pakistani CNIC (e.g., 35201-1234567-1 or 3520112345671)
  sanitized = sanitized.replace(/\b\d{5}[-\s]?\d{7}[-\s]?\d{1}\b/g, '[CNIC REDACTED]');

  // 3. Redact Pakistani Mobile Numbers (03XX-XXXXXXX or +92-3XX-XXXXXXX)
  sanitized = sanitized.replace(/(?:\+92|0092|0)?\s?3\d{2}[-\s]?\d{7}\b/g, '[PHONE REDACTED]');

  // 4. Redact Email addresses
  sanitized = sanitized.replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, '[EMAIL REDACTED]');

  // 5. Redact Pakistani IBANs (e.g. PK36SCBL0000001123456702)
  sanitized = sanitized.replace(/\bPK\d{2}[A-Z]{4}\d{16}\b/gi, '[IBAN REDACTED]');

  // 6. Redact Credit/Debit card numbers (16 digits)
  sanitized = sanitized.replace(/\b(?:\d{4}[-\s]?){3}\d{4}\b/g, '[CARD REDACTED]');

  // 7. Restore allowed emergency hotlines
  hotlineReplacements.forEach(({ placeholder, match }) => {
    sanitized = sanitized.replace(placeholder, match);
  });

  return sanitized;
}

/**
 * Screen generated text for unauthorized prescription verbs or definitive diagnosing.
 *
 * @param {string} text
 * @returns {{ passed: boolean, violation: string|null, sanitizedText: string }}
 */
function screenPrescriptionAndDiagnosis(text) {
  if (!text || typeof text !== 'string') return { passed: true, violation: null, sanitizedText: text };

  // Check unauthorized prescribing statements
  const prescribingPatterns = [
    /\b(i prescribe|i am prescribing|take \d+\s?mg of|start taking \d+\s?mg)\b/i,
    /\b(you must take \d+\s?mg|take \d+\s?mg|you must inject|increase your insulin dose to|take this medicine twice)\b/i,
  ];

  for (const pattern of prescribingPatterns) {
    if (pattern.test(text)) {
      return {
        passed: false,
        violation: 'UNAUTHORIZED_PRESCRIPTION_ATTEMPT',
        sanitizedText:
          'Medzoos Copilot provides educational guidance only and cannot prescribe medications — prescription medications must only be adjusted by your licensed doctor. Please consult a clinician.',
      };
    }
  }

  // Check definitive diagnostic assertions
  const diagnosingPatterns = [
    /\b(you definitely have|i diagnose you with|you are suffering from confirmed|you are suffering from)\b/i,
  ];

  for (const pattern of diagnosingPatterns) {
    if (pattern.test(text)) {
      return {
        passed: false,
        violation: 'DEFINITIVE_DIAGNOSIS_ATTEMPT',
        sanitizedText: text.replace(
          pattern,
          'These symptoms may be consistent with, but require clinical evaluation for'
        ),
      };
    }
  }

  return { passed: true, violation: null, sanitizedText: text };
}

/**
 * Verify numerical grounding: verifies that medical metrics generated by LLM
 * are grounded in the verified chunks or patient-reported context.
 *
 * @param {string} llmText
 * @param {Array} retrievedChunks
 * @returns {{ isGrounded: boolean, ungroundedNumbers: string[] }}
 */
function verifyNumericalGrounding(llmText, retrievedChunks = []) {
  if (!llmText || typeof llmText !== 'string') return { isGrounded: true, ungroundedNumbers: [] };

  // Combine content from all verified retrieved chunks
  const chunkText = retrievedChunks.map((c) => c.content || '').join(' ');

  // Extract explicit medical numbers (e.g. "15-15", "126 mg/dL", "6.5%", "130/80")
  const medicalNumberMatches =
    llmText.match(/\b\d+(?:\.\d+)?(?:\s?-\s?\d+(?:\.\d+)?)?\s*(?:%|\b(?:mg\/dl|mmol\/l|mmhg|bpm|°f|°c|liters?|litres?|days?|hours?)\b)/gi) || [];

  const ungroundedNumbers = [];

  for (const match of medicalNumberMatches) {
    const rawNumber = match.replace(/%|mg\/dl|mmol\/l|mmhg|bpm|°f|°c|liters?|litres?|days?|hours?/gi, '').trim();
    // If the exact number or range is neither in chunk text nor common general numbers (e.g. 15, 2, 7), flag it
    const escapedNumber = rawNumber.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (!new RegExp(escapedNumber).test(chunkText) && !['15', '2', '24', '1', '7', '10', '4'].includes(rawNumber)) {
      ungroundedNumbers.push(match);
    }
  }

  return {
    isGrounded: ungroundedNumbers.length === 0,
    ungroundedNumbers,
  };
}

/**
 * Verify that all citations in the response are part of the verified retrieved chunks.
 *
 * @param {string[]} citations
 * @param {Array} retrievedChunks
 * @returns {string[]} Verified citations only
 */
function verifyCitations(citations = [], retrievedChunks = []) {
  if (!Array.isArray(citations) || citations.length === 0) return [];
  if (!Array.isArray(retrievedChunks) || retrievedChunks.length === 0) return [];

  const validSources = new Set(
    retrievedChunks.map((c) => (c.source_name || '').toLowerCase())
  );

  return citations.filter((cit) => {
    const lower = cit.toLowerCase();
    for (const valid of validSources) {
      if (valid && lower.includes(valid)) return true;
    }
    return false;
  });
}

/**
 * Master Guardrail Runner
 *
 * Runs all validation and sanitization steps on LLM-generated or pipeline output.
 *
 * @param {object} params
 * @param {string} params.text
 * @param {Array} [params.retrievedChunks]
 * @param {string[]} [params.citations]
 * @param {object} [params.triageResult]
 * @returns {{ text: string, citations: string[], guardrailsPassed: boolean, violations: string[] }}
 */
function applySafetyGuardrails({
  text,
  retrievedChunks = [],
  citations = [],
  triageResult = {},
}) {
  const violations = [];

  // 1. PII Sanitization
  let outputText = sanitizePii(text || '');

  // 2. Prescription and Diagnosis Screen
  const prescCheck = screenPrescriptionAndDiagnosis(outputText);
  if (!prescCheck.passed) {
    violations.push(prescCheck.violation);
    outputText = prescCheck.sanitizedText;
  }

  // 3. Numerical Grounding Screen
  if (retrievedChunks.length > 0) {
    const numCheck = verifyNumericalGrounding(outputText, retrievedChunks);
    if (!numCheck.isGrounded) {
      violations.push(`UNGROUNDED_NUMBERS: ${numCheck.ungroundedNumbers.join(', ')}`);
    }
  }

  // 4. Citation Whitelist Verification
  const validCitations = verifyCitations(citations, retrievedChunks);

  return {
    text: outputText,
    citations: validCitations.length > 0 ? validCitations : citations,
    guardrailsPassed: violations.length === 0,
    violations,
  };
}

module.exports = {
  sanitizePii,
  screenPrescriptionAndDiagnosis,
  verifyNumericalGrounding,
  verifyCitations,
  applySafetyGuardrails,
};
